### PR TITLE
move react dependency to devDependencies

### PR DESCRIPTION
**Pull request by blackbing**
react should not be dependency for a react-base library. move react to devDependencies.

### CODE REVIEW

**Comment by asbjornenge** [comment]
@blackbing would perhaps the most correct thing be to list react under peerDependencies?

**Comment by asbjornenge** [comment]
Controversial topic apparently :stuck_out_tongue_closed_eyes: https://github.com/yahoo/react-intl/issues/79 https://github.com/rackt/react-router/issues/98

**Comment by blackbing** [comment]
Yap, actually it should be upgrade react 0.12 support, I think it should be set correctly and  then upgrade react version. I use it in my project so I can help to test it.

**Comment by asbjornenge** [comment]
As you can see by the commit I went the peerDependencies route with >= instead of ^ :smile: Hope that works for you :+1:

**Pull request closed without merging**
